### ISSUE TITLE
Access to everyone without allowed_user_id

### ISSUE THREAD

**Issue by TimmekHW** [capslock/stable-diffusion-bot#8]
Access to everyone without allowed_user_id.

how to allow access to everyone without the need to enter telegram_id? so that anyone who wrote could interact with it.

![IMG_0655](https://github.com/capslock/stable-diffusion-bot/assets/94626112/b5945903-943d-40a0-a9be-ceca6a5c6b7a)

**Comment by capslock** [comment]
If you supply a chat id instead of a user id, you can allow everyone in a group chat to access the bot without needing to add each individual user's id into the list. Is that helpful for your use case?

Right now there's no way to just allow anyone who messages the bot to interact with it, as that would mean anyone on telegram who found the bot could use it. But if that's what you want (and the above doesn't work for you), I can add a new config option to allow that.

**Comment by TimmekHW** [comment]
Да, такая опция необходима. Просто, если использовать боту в общем чате, то нужно сделать триггерную фразу. например «/gen»

**Comment by TimmekHW** [comment]
I'm sorry, the "/gen" command works

**Comment by TimmekHW** [comment]
I downloaded the latest version of the bot. I saw the update. How do I enable the feature so that anyone can use it?

**Comment by TimmekHW** [comment]
@capslock I downloaded the latest version of the bot. I saw the update. How do I enable the feature so that anyone can use it?

**Comment by TimmekHW** [comment]
how to remove the /Img2ImgSettings and /Txt2ImgSettings buttons?

**Comment by TimmekHW** [comment]
The new feature works and works great. Thank you! But before I could simply remove the /Img2ImgSettings buttons, but now Cargo does not compile the code without them :(

**Comment by capslock** [comment]
Do you mean like in #6? I just tried it out and removing the lines still works for me and compiles fine. If you post the error that you're getting I can try to help.

**Comment by TimmekHW** [comment]
Yes, it helped.
Thanks to you, I can continue to share 4090 power for free for people! 
I think you would like to see how much your project helps others. Rate https://t.me/aniworld_model_bot

**Comment by capslock** [comment]
That's great!

I'm happy that my small side project is able to help you share generative AI with others!
